version: 2

models:
  - name: stg_fixtures
    description: Cleaned and standardized match-level fixtures.
    columns:
      - name: match_id
        tests:
          - not_null
          - unique

      - name: match_date
        tests:
          - not_null

      - name: home_team
        tests:
          - not_null

      - name: away_team
        tests:
          - not_null
