version: 2

sources:
  - name: football
    schema: raw
    description: "Raw football data ingested from API-Football"

    tables:
      - name: fixtures
        description: "All match fixtures (both completed and upcoming)"
        columns:
          - name: season
            description: "Season year (start year)"
          - name: date
            description: "Match date"
          - name: home_team
            description: "Home team name"
          - name: away_team
            description: "Away team name"
          - name: home_goals
            description: "Goals scored by home team (NULL for future fixtures)"
          - name: away_goals
            description: "Goals scored by away team (NULL for future fixtures)"
          - name: status
            description: "Match status: FT (finished), NS (not started), TBD, PST (postponed)"
          - name: fixture_id
            description: "API fixture ID"