name: 'predict_may'
version: '1.0.0'
config-version: 2

profile: predict_may

model-paths: ["models"]

models:
  predict_may:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table
